### PR TITLE
Bugfix/country selection skipped unexpectedly

### LINKED ISSUE #1444: Country selection is skipped unexpectedly
### What was the expected behaviour?

Given the options `documentTypes: { driving_licence: true, national_identity_card: true}` I expected to see the country-selection screen.

### What happened instead?

The country-selection screen was skipped (as if I had set the country property to `{country:null}`).
However setting this property to any other value makes the selection screen appear again.

### Version info:

- 6.7.0/6.8.0
- Linux
- Firefox
- Node 12

### Steps to reproduce:

Start the Onfido document check and click on "driver license".

### PR DESCRIPTION
**Pull request by kopijunkie**
# Problem
From Web SDK v6.6.0 integrations that have enabled document type options using the boolean configuration option skips the Country Selection screen instead of displaying like it was in previous versions as of v6.3.1. Fixes #1444 

# Solution
- Add a conditional check for when a document type's configuration is just a boolean value
- Add UI tests to ensure this configuration's UX works as intended

## Checklist

_put `n/a` if item is not relevant to PR changes_

- [x] Has the CHANGELOG been updated?
- [ ] Has the README been updated?
- [ ] Has the CONTRIBUTING doc been updated?
- [ ] Has the RELEASE_GUIDELINES been updated?
- [ ] Has the TESTING_GUIDELINES been updated?
- [ ] Has the MIGRATION doc been updated for any MAJOR breaking changes?
- [ ] Has the MIGRATION doc been updated for any MINOR breaking changes, including any translation strings or keys changes?
- [x] Have any new automated tests been implemented or the existing ones changed?
- [ ] Have any new manual tests been written down or the existing ones changed?
- [ ] Have any new strings been translated or the existing ones changed?

### CODE REVIEW

File: src/components/Router/StepComponentMap.ts [hunk 1]
```diff
@@ -267,7 +267,9 @@ const buildDocumentComponents = (
   )
   const showCountrySelection =
     showCountrySelectionForSinglePreselectedDocument ||
-    (!hasOnePreselectedDocument && !supportedCountry && countryCode !== null)
+    (!hasOnePreselectedDocument &&
+      !supportedCountry &&
+      (countryCode !== null || configForDocumentType === true))
```
Comment (ethan605) [inline src/components/Router/StepComponentMap.ts:272]: I believe this could be broken into smaller & more verbose checks :thinking:

File: src/demo/demoUtils.ts [hunk 2]
```diff
@@ -25,6 +25,7 @@ export type QueryParams = {
   liveness?: StringifiedBoolean
   multiDocWithInvalidPresetCountry?: StringifiedBoolean
   multiDocWithPresetCountry?: StringifiedBoolean
+  multiDocBooleanWithCountrySelection?: StringifiedBoolean
```
Comment (ethan605) [inline src/demo/demoUtils.ts:28]: IMO this could be
```suggestion
  multiDocWithBooleanValues?: StringifiedBoolean
```

File: src/demo/demoUtils.ts [hunk 3]
```diff
@@ -130,6 +131,13 @@ const getPreselectedDocumentTypes = (): Partial<
     }
   }
 
+  if (queryParamToValueString.multiDocBooleanWithCountrySelection === 'true') {
```
Comment (ethan605) [inline src/demo/demoUtils.ts:134]:
```suggestion
  if (queryParamToValueString.multiDocWithBooleanValues === 'true') {
```

**Review by ethan605 — APPROVED** [review]
LGTM!

File: src/components/Router/StepComponentMap.ts (hunk 1 above)
Comment (kopijunkie) [reply src/components/Router/StepComponentMap.ts]: Agree. I've taken another stab at it, but if you have any ideas for further improvements, feel free to suggest.

File: src/components/Router/StepComponentMap.ts [hunk 4]
```diff
@@ -265,9 +265,14 @@ const buildDocumentComponents = (
     countryCode,
     documentType
   )
+  const hasMultipleDocumentsWithUnsupportedCountry =
+    !hasOnePreselectedDocument && !supportedCountry
+  const hasCountryCodeNullOrBooleanDocumentTypeFlag =
```
Comment (stefaniacardenas) [inline src/components/Router/StepComponentMap.ts:270]: `hasCountryCodeNullOrBooleanDocumentTypeFlag` should probably be renamed to `hasCountryCodeOrDocumentTypeFlag` because in the code you are checking that `countryCode` is not `null`

File: src/components/Router/StepComponentMap.ts [hunk 5]
```diff
@@ -265,9 +265,14 @@ const buildDocumentComponents = (
...
+    countryCode !== null || configForDocumentType === true
```
Comment (stefaniacardenas) [inline src/components/Router/StepComponentMap.ts:271]: Why not 
```suggestion
    countryCode !== null || configForDocumentType
```

File: src/components/Router/StepComponentMap.ts (hunk 4 above)
Comment (kopijunkie) [reply src/components/Router/StepComponentMap.ts:270]: Good point. Will rename it.

File: src/components/Router/StepComponentMap.ts (hunk 5 above)
Comment (kopijunkie) [reply src/components/Router/StepComponentMap.ts]: Actually, realised this would need to be a strict check for a boolean `true` value since `configForDocumentType` could also be an object which is truthy also.

**Review by stefaniacardenas — APPROVED** [review]
